// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_Cw4_s29792.Infrastructure;

#nullable disable

namespace PJATK_APBD_Cw4_s29792.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512212226_addModels")]
    partial class addModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_Cw4_s29792.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s29792.Models.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)");

                    b.HasKey("Id");

                    b.ToTable("PCs");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s29792.Models.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s29792.Models.PcComponent", b =>
                {
                    b.HasOne("PJATK_APBD_Cw4_s29792.Models.Component", "Component")
                        .WithMany("PcComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw4_s29792.Models.Pc", "Pc")
                        .WithMany("PcComponents")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s29792.Models.Component", b =>
                {
                    b.Navigation("PcComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw4_s29792.Models.Pc", b =>
                {
                    b.Navigation("PcComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
